version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: endisilveira/albicocche-backend:latest  # Nome da imagem especificado aqui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run build && node dist/index.js"
