services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      PORT: ${PORT}
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/dist
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run build && node dist/server.js"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  postgres_data:
