version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: endisilveira/albicocche-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/database
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_email_password
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run dev"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
